FirstInFirstAid/Controllers/BackupController.cs
using FirstInFirstAid.Helpers;
using FirstInFirstAid.Models.Helpers;
using log4net;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace FirstInFirstAid.Controllers
{
    [Authorize]
    public class BackupController : Controller
    {
        private static readonly ILog logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private BackupManager backupHelper;

        //System's database backup folder. Usually resides in SQL Server installation directory
        private string backupFolder;

        public BackupController()
        {
            backupHelper = new BackupManager();
            backupFolder = backupHelper.GetBackupFolder();
        }

        [HttpGet]
        public ActionResult Index()
        {
            var dir = new DirectoryInfo(backupFolder);
            FileInfo[] files = dir.GetFiles("*.bak");
            List<BackupFile> items = new List<BackupFile>();
            foreach (var file in files)
            {
                BackupFile backupFile = new BackupFile
                {
                    FileName = file.Name,
                    CreatedTime = file.CreationTime                   
                };

                items.Add(backupFile);
            }
            ViewBag.Message = TempData["Message"]?.ToString();
            return View(items);
        }

        [HttpPost]
        public ActionResult CreateBackup()
        {
            backupHelper.CreateBackup();
            return RedirectToAction("Index");
        }

    
        public ActionResult Download(string backupName)
        {
           
            string filepath = backupFolder + "\\" + backupName;
            byte[] filedata = System.IO.File.ReadAllBytes(filepath);
            string contentType = MimeMapping.GetMimeMapping(filepath);

            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = backupName,
                Inline = true,
            };

            Response.AppendHeader("Content-Disposition", cd.ToString());

            return File(filedata, contentType);
        }

        [HttpPost]
        public ActionResult Restore(HttpPostedFileBase postedFile)
        {
            if (postedFile != null)
            {                
                string uploadsDirPath = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(uploadsDirPath))
                {
                    Directory.CreateDirectory(uploadsDirPath);
                }
                string filePath = uploadsDirPath + Path.GetFileName(postedFile.FileName);
                postedFile.SaveAs(filePath);
                backupHelper.Restore(filePath);
                backupHelper.CleanUploadsDir(uploadsDirPath);
                ViewBag.Message = "File uploaded successfully.";
            }
            TempData["Message"] = "Database restored successfully. Please restart the system.";
            return RedirectToAction("Index");
        }
    }
}

FirstInFirstAid/Controllers/DashboardController.cs
using System.Web.Mvc;

namespace FirstInFirstAid.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }

    }
       
}

FirstInFirstAid/Controllers/EventsController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Reflection;
using FirstInFirstAid.DAL;
using FirstInFirstAid.Models;
using log4net;
using System;
using System.Collections.Generic;

namespace FirstInFirstAid.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private static readonly ILog logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private FirstInFirstAidDBContext db = new FirstInFirstAidDBContext();

        // GET: Events
        public ActionResult Index()
        {
            logger.Debug("Getting the Event list");
            var events = db.Events.Include(c => c.Client);
            return View(events.ToList());
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            ViewBag.Id = new SelectList(db.Clients, "Id", "Name");
            //Select List for duty type
            var dutyType = from Coverage d in Enum.GetValues(typeof(Coverage))
                           select new { ID = (int)d, Name = d.ToString() };
            ViewBag.CoverageSelectList = dutyType.ToList();
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EventName,InvoiceNumber,HourlyRate,BusinessId,EventState")]Event ev3nt, int clientId)
        {                        

            if (ModelState.IsValid)
            {
                Client client = db.Clients.Include(e => e.Events).Where(i => i.Id == clientId).First();
                client.Events.Add(ev3nt);        
                db.SaveChanges();
                logger.InfoFormat("Event Created, Name : {0}, Id: {1}", ev3nt.EventName, ev3nt.Id);
                var id = ev3nt.Id;
                return RedirectToAction("Edit", new
                {
                    id = ev3nt.Id,
                });
            }
            ViewBag.Id = new SelectList(db.Clients, "Id", "Name");
            return View(ev3nt);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                logger.Warn("Received null Event Id to modify");
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Include(s => s.EventSegments).Include(c => c.Client).Where(x => x.Id == id).First();
            if (@event == null)
            {
                logger.Warn("Received null Event Id to modify");
                return HttpNotFound();
            }
            var clientList = from Client v in db.Clients select new { ID = v.Id, Name = v.Name };
            ViewBag.Clients = new SelectList(clientList, "ID", "Name", @event.Client.Id);
            //Select List for duty type
            var dutyType = from Coverage d in Enum.GetValues(typeof(Coverage))
                           select new { ID = (int)d, Name = d.ToString() };
            ViewBag.CoverageSelectList = dutyType.ToList();
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EventName,InvoiceNumber,HourlyRate,BusinessId,EventState")] Event @event, int clientId)
        {
          
            if (ModelState.IsValid)
            {
                logger.DebugFormat("Modifying Event of the Name: {0} and Id:{}", @event.EventName, @event.Id);
                Event dbEvent = db.Events.Include(c => c.EventSegments).Include(x => x.Client).Where(i => i.Id == @event.Id).First();

                //Updating the client
                Client existingClient = dbEvent.Client;
                if (existingClient != null) { 
                    if (clientId > 0 && clientId != existingClient.Id) {
                        Client newClient = db.Clients.Include(e => e.Events).Where(i => i.Id == clientId).First();
                        existingClient.Events.Remove(dbEvent);
                        newClient.Events.Add(dbEvent);
                    } 
                } else if (clientId > 0) 
                {
                    Client newClient = db.Clients.Include(e => e.Events).Where(i => i.Id == clientId).First();
                    newClient.Events.Add(dbEvent);
                }

                //updating the Event fields
                dbEvent.EventName = @event.EventName;
                dbEvent.EventState = @event.EventState;
                dbEvent.BusinessId = @event.BusinessId;
                dbEvent.HourlyRate = @event.HourlyRate;
                dbEvent.InvoiceNumber = @event.InvoiceNumber;

                db.SaveChanges();
                logger.InfoFormat("Event successfully modified, Name: {0}, Id: {1}", dbEvent.EventName, @event.Id);
                return RedirectToAction("Index");
            }
            var clientList = from Client v in db.Clients select new { ID = v.Id, Name = v.Name };
            ViewBag.Clients = new SelectList(clientList, "ID", "Name", @event.Client.Id);
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                logger.Warn("Received null Event Id to delete");

                return Content("{\"Type\":\"Warn\", \"Message\":\"Received null Event Id to delete\"}");

            }
            else
            {

                Event @event = db.Events.Include(e => e.EventSegments).Where(i => i.Id == id).First();
                if (@event == null)
                {
                    logger.WarnFormat("Event not found to delete, Id: {0}", id);
                    return Content("{\"Type\":\"Warn\", \"Message\":\"Event not found to delete with the Id:" + id + "\"}");
                }
                else if (@event.EventSegments.Count() > 0)
                {
                    return Content("{\"Type\":\"WarnConfirm\", \"Message\":\"Are you sure? This Event is associated with " + @event.EventSegments.Count + " Event Segment/s. Continuing will delete all of it.\", \"Id\": \" " + @event.Id + "\"}");
                }
                else
                {
                    return Content("{\"Type\":\"Confirm\", \"Message\":\"Are you sure you want to delete the Event: " + @event.EventName + "\", \"Id\": \" " + @event.Id + "\"}");
                }
            }
        }

        // POST: Events/Delete/5
        [HttpPost]
        public JsonResult DeleteConfirmed(int id)
        {
            Event eventVar = db.Events.Find(id);            
            db.Events.Remove(eventVar);
            db.SaveChanges();
            logger.InfoFormat("Event deleted, Name: {0}, Id: {1}", eventVar.EventName, eventVar.Id);
            return Json("Successfully deleted the Event: " + eventVar.EventName);
        }

        public JsonResult GetClients() // its a GET, not a POST
        {
            return Json(db.Clients, JsonRequestBehavior.AllowGet);
        }

        
        public JsonResult getEventState()
        {
            List<object> list = new List<object>();
            foreach (Event ev3nt in db.Events)
            {                
                list.Add(new { ID = ev3nt.Id, State = ev3nt.EventState});                
            }

            return Json(list, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FirstInFirstAid/Controllers/VenuesController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FirstInFirstAid.DAL;
using FirstInFirstAid.Models;
using log4net;
using System.Reflection;

namespace FirstInFirstAid.Controllers
{
    [Authorize]
    public class VenuesController : Controller
    {
        private static readonly ILog logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private FirstInFirstAidDBContext db = new FirstInFirstAidDBContext();

        public JsonResult VenueExists(string VenueName, int? Id)
        {
            var validateName = db.Venues.FirstOrDefault(x => x.VenueName == VenueName && x.Id != Id);

            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Venues
        public ActionResult Index()
        {
            logger.Debug("Getting the Venue list");
            return View(db.Venues.ToList());
        }

        // GET: Venues/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Venues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,VenueName,Address")] Venue venue)
        {
            if (ModelState.IsValid)
            {                
                db.Venues.Add(venue);
                db.SaveChanges();
                logger.InfoFormat("Venue Created, Name : {0}, Id: {1}", venue.VenueName, venue.Id);
                return RedirectToAction("Index");                
            }
            return View(venue);
        }

        // GET: Venues/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                logger.Warn("Received null Venue Id to modify");
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venue venue = db.Venues.Include(s => s.Address).Where(x => x.Id == id).First();
            if (venue == null)
            {
                logger.WarnFormat("Venue not found to modify, Id: {0}", id);
                return HttpNotFound();
            }
            return View(venue);
        }

        // POST: Venues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,VenueName,Address")] Venue venue)
        {
            if (ModelState.IsValid)
            {
                logger.DebugFormat("Modifying Venue of the Name: {0} and Id:{}", venue.VenueName, venue.Id);
                db.Entry(venue).State = EntityState.Modified;
                if (venue.Address != null)
                {
                    if (venue.Address.Id > 0)
                    {
                        db.Entry(venue.Address).State = EntityState.Modified;
                    }
                    else
                    {
                        db.Entry(venue.Address).State = EntityState.Added;
                    }

                } 
                
                db.SaveChanges();
                logger.InfoFormat("Venue modified, Name: {0}, Id: {1}", venue.VenueName, venue.Id);
                return RedirectToAction("Index");
            }
            return View(venue);
        }

        // GET: Venues/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                logger.Warn("Received null Venue Id to delete");

                return Content("{\"Type\":\"Warn\", \"Message\":\"Received null Venue Id to delete\"}");

            }
            else
            {

                Venue venue = db.Venues.Include(e => e.EventSegments).Where(i => i.Id == id).First();
                if (venue == null)
                {
                    logger.WarnFormat("Venue not found to delete, Id: {0}", id);
                    return Content("{\"Type\":\"Warn\", \"Message\":\"Venue not found to delete with the Id:" + id + "\"}");
                }
                else if (venue.EventSegments.Count() > 0)
                {
                    return Content("{\"Type\":\"Warn\", \"Message\":\"The Venue is associated with one or more Event Segments. Please delete the related Event Segments or assign another Venue to those Event Segments\"}");
                }
                else
                {
                    return Content("{\"Type\":\"Confirm\", \"Message\":\"Are you sure you want to delete the Venue: " + venue.VenueName + "\", \"Id\": \" " + venue.Id + "\"}");
                }
            }
        }

        // POST: Venues/Delete/5
        [HttpPost]
        public JsonResult DeleteConfirmed(int id)
        {
            Venue venue = db.Venues.Find(id);
            db.Venues.Remove(venue);
            db.SaveChanges();
            logger.InfoFormat("Venue deleted, Name: {0}, Id: {1}", venue.VenueName, venue.Id);
            return Json("Successfully deleted the venue: " + venue.VenueName);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FirstInFirstAid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Software Application</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
        <!--Custom css file by Anu-->
    @Styles.Render("~/Content/custom-styles.css")
        <!--Font Aweson bundle-->
    @Styles.Render("~/Content/font-awesome.min.css")
</head>
<body>
    <!--Top Navigation-->
    <div id="topbar" class="navbar navbar-inverse navbar-fixed-top" role="banner">
        <div class="container-fluid">
            <!--Mobile dropdown-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">FISFA | FIFAS</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse" role="navigation">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#"> <i class="fa fa-user"></i> Hi, Administrator <b class="caret"></b> </a>
                        <ul class="dropdown-menu">
                            @using (Html.BeginForm("LogOff", "Accounts", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                                <li><a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-sign-out"></i>Log Off</a></li>
                            }
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">Dashboard</a>
                    </li>
                </ul>
                <!-- <ul class="nav navbar-nav navbar-right">
                     <li>
                         <a href="#">Calender</a>
                     </li>
                 </ul>-->
            </div>
        </div>
    </div>

    <!--Sidebar-->
    <div class="content">
        <div class="sidebar">
            <!--Sidebar mobile drop down-->
            <div class="navbar-header">
                <div class="sidebar-dropdown">
                    <a id="main-menu" href="#" class="navbar-toggle" role="button" data-toggle="collapse" data-target=".navbar-collapse2">Main Menu</a>
                </div>
            </div>
            <nav class="sidebar-inner collapse navbar-collapse navbar-collapse2" role="navigation">
                <ul class="nav-sidebar">
                    <li class="nred level1">
                        <a href="@Url.Action("Index", "Dashboard")" class="fisfa-h"> <i class="fa fa-dashboard"></i> Dashboard </a>

                    </li>
                    <li class="nblue level1">
                        <a href="@Url.Action("Index", "EventSegments")" class="fisfa-es"> <i class="fa fa-calendar"></i> Event Segments </a>

                    </li>
                    <li class="has_submenu nblue level1">

                        <a class="fisfa-e"> <i class="fa fa-calendar"></i> Events<span class="pull-right"><i class="fa fa-sort-down"></i></span> </a>
                        <ul>
                            <li>  @Html.ActionLink("All Events", "Index", "Events") </li>
                            <li>  @Html.ActionLink("Add New", "Create", "Events") </li>
                        </ul>
                    </li>
                    <li class="has_submenu nblue level1">

                        <a class="fisfa-c"> <i class="fa fa-user"></i> Clients<span class="pull-right"><i class="fa fa-sort-down"></i></span> </a>
                        <ul>
                            <li> @Html.ActionLink("All Clients", "Index", "Clients")  </li>
                            <li> @Html.ActionLink("Add New", "Create", "Clients") </li>
                        </ul>
                    </li>

                    <li class="has_submenu nblue level1">

                        <a class="fisfa-t"> <i class="fa fa-group"></i> Trainers<span class="pull-right"><i class="fa fa-sort-down"></i></span></a>
                        <ul>
                            <li> @Html.ActionLink("All Trainers", "Index", "Trainors")  </li>
                            <li> @Html.ActionLink("Add New", "Create", "Trainors") </li>
                        </ul>
                    </li>


                    <li class="has_submenu nblue level1">

                        <a class="fisfa-v"> <i class="fa fa-map-marker"></i> Venues<span class="pull-right"><i class="fa fa-sort-down"></i></span> </a>
                        <ul>
                            <li> @Html.ActionLink("All Venues", "Index", "Venues")  </li>
                            <li> @Html.ActionLink("Add New", "Create", "Venues") </li>
                        </ul>
                    </li>

                    <li class="has_submenu nblue level1">

                        <a class="fisfa-eq"> <i class="fa fa-suitcase"> </i> Equipment<span class="pull-right"><i class="fa fa-sort-down"></i></span> </a>
                        <ul>
                            <li> @Html.ActionLink("Equipment Allocations", "Index", "Equipments")  </li>
                            <li> @Html.ActionLink("Add New", "Create", "Equipments") </li>
                        </ul>
                    </li>
                    <li class="nblue">
                        <a href="@Url.Action("Index", "Backup")" class="fisfa-eq"> <i class="fa fa-hdd-o"> </i> Backup/ Restore<span class="pull-right"></span> </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="main">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - First in Teams Pty Ltd</p>
        </footer>
    </div>


    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <!--Including moments.js for Full Calendar by Anu-->
    <script src="~/Scripts/moment.min.js"></script>

    <!--Including jquery client side validation by Anu-->
    @Scripts.Render("~/bundles/jqueryval")

    <!-- Including the jquery-ui script and style bundles by Anu-->
    @Scripts.Render("~/bundles/jquery-ui")
    @Styles.Render("~/Content/jquery-ui-timepicker-addon.min.css")

    <!--Include jquery data tables-->
    <link href="~/Content/datatables.min.css" rel="stylesheet" />
    <link href="~/Content/responsive.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/dataTables.bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/datatables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap4.min.js"></script>

    <!--Including Full Calendar by Anu-->
    <link href="~/Content/fullcalendar.min.css" rel="stylesheet" />
    <script src="~/Scripts/fullcalendar.min.js"></script>

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            /*Add current class to current page*/
            $(".level1").each(function () {
                if (window.location.href.indexOf($(this).find('a:first').attr('href')) > -1) {
                    $(this).addClass('current').siblings().removeClass('current');
                }
            });

            $(".nav-sidebar > li> ul> li").each(function () {
                if (window.location.href.indexOf($(this).find('a:first').attr('href')) > -1) {
                    $(this).children('a').addClass('active').siblings().removeClass('active');

                    $(this).parent().css("display", "block");
                    $(this).parent().parent().addClass('current');
                }

            });

            $(".has_submenu > a").click(function (e) {
                e.preventDefault();
                var menu_li = $(this).parent("li");
                var menu_ul = $(this).next("ul");

                if (menu_li.hasClass("open")) {
                    menu_ul.slideUp(350);
                    menu_li.removeClass("open")
                }
                else {
                    $(".nav-sidebar > li > ul").slideUp(350);
                    $(".nav-sidebar > li").removeClass("open");
                    menu_ul.slideDown(350);
                    menu_li.addClass("open");
                    menu_ul.css("display", "block");
                }
            })

            $('.mdtable').dataTable({
            });

        });
        /* Code to fix "field must be a date" issue in Chrome and VFirefox */
        $.validator.addMethod('date',
            function (value, element) {
                if (this.optional(element)) {
                    return true;
                }
                var valid = true;
                try {
                    $.datepicker.parseDate('dd.M.yy', value);
                }
                catch (err) {
                    valid = false;
                }
                return valid;
            });
        // function to fix DOB issue in Firefox browser
        /*$(function () {
                $.validator.methods.date = function (value, element) {
                return this.optional(element) || moment(value, "L" , true).isValid();
            }
        });*/
        
    </script>

    <div id="warnModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div id="warnModalheader" class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Warning!</h4>
                </div>
                <div id="warnModalBody" class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div id="confirmModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div id="confirmModalheader" class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Info</h4>
                </div>
                <div id="confirmModalBody" class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button id="delButton" type="button" class="btn btn-danger" data-dismiss="modal">Yes</button>
                </div>
            </div>
        </div>
    </div>


    <div id="successModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div id="successModalheader" class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Success</h4>
                </div>
                <div id="successModalBody" class="modal-body">
                </div>
                <div class="modal-footer" id="confirmFooter">
                    <button type="button" onclick="javascript:window.location.reload()" class="btn btn-default" data-dismiss="modal">Ok</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>